<div>
  <h2>
    About.
  </h2>
  <div>
    This is a blog.
  </div>
</div>
          <div id="global-tag-list">
          <h2>
            Tags
          </h2>
          <ul>
            <li><a class="reference" href="/categories/bokeh/">bokeh</a> (1)</li>
            <li><a class="reference" href="/categories/equation/">equation</a> (1)</li>
            <li><a class="reference" href="/categories/holoviews/">holoviews</a> (1)</li>
            <li><a class="reference" href="/categories/introduction/">Introduction</a> (1)</li>
            <li><a class="reference" href="/categories/jupyter/">jupyter</a> (2)</li>
            <li><a class="reference" href="/categories/mpld3/">mpld3</a> (1)</li>
            <li><a class="reference" href="/categories/notebook/">notebook</a> (2)</li>
            <li><a class="reference" href="/categories/plotly/">plotly</a> (2)</li>
            <li><a class="reference" href="/categories/plotting/">plotting</a> (1)</li>
          </ul>
        </div>